baseURL = "https://anugerah.netlify.app/"
languageCode = "en-us"
title = "Anugerah's Digital Garden"
theme = "archie"
copyright = " Anugerah"

customcss = "css/main.css"

summaryLength= 5

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2
  

[params]
	mode="toggle" # color-mode â†’ light,dark,toggle or auto

[[params.social]]
  name= "Instagram"
  icon= "instagram"
  url= "https://www.instagram.com/brflook/"
  
[[params.social]]
  name= "Email"
  icon= "mail"
  url= "mailto:nugehoodg@gmail.com"

[[params.social]]
  name= "GitHub"
  icon= "github"
  url= "https://github.com/nugehood"

[[params.social]]
  name= "Rss"
  icon= "rss"
  url= "/index.xml"

# Main menu Items
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about" 
  weight = 3

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 5